import Foundation

public enum ClipboardCaptureRejection: Equatable, Sendable {
    case sensitiveType
    case excludedApplication
    case tooLarge
}

public enum ClipboardCaptureDecision: Equatable, Sendable {
    case accept
    case reject(ClipboardCaptureRejection)
}

public struct ClipboardPrivacyPolicy: Sendable {
    public static let `default` = ClipboardPrivacyPolicy()

    private static let sensitiveTypeNames: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private let excludedBundleIDs: Set<String>
    private let maximumTextBytes: Int
    private let maximumImageBytes: Int

    public init(
        excludedBundleIDs: Set<String> = [],
        maximumTextBytes: Int = 1_048_576,
        maximumImageBytes: Int = 40 * 1_024 * 1_024
    ) {
        self.excludedBundleIDs = excludedBundleIDs
        self.maximumTextBytes = maximumTextBytes
        self.maximumImageBytes = maximumImageBytes
    }

    public func decision(
        kind: ClipboardItemKind,
        typeNames: Set<String>,
        sourceBundleID: String?,
        payloadBytes: Int
    ) -> ClipboardCaptureDecision {
        if !typeNames.isDisjoint(with: Self.sensitiveTypeNames) {
            return .reject(.sensitiveType)
        }
        if let sourceBundleID, excludedBundleIDs.contains(sourceBundleID) {
            return .reject(.excludedApplication)
        }

        switch kind {
        case .text, .link:
            if payloadBytes > maximumTextBytes {
                return .reject(.tooLarge)
            }
        case .image:
            if payloadBytes > maximumImageBytes {
                return .reject(.tooLarge)
            }
        case .files:
            break
        }

        return .accept
    }
}
