import Foundation
import ClipboardHistoryCore

@main
struct ClipboardHistoryCoreChecks {
    static func main() throws {
        let source = ClipboardSource(appName: "Notes", bundleID: "com.apple.Notes")
        let first = ClipboardCandidate(
            payload: .text("hello\r\nworld"),
            source: source,
            capturedAt: Date(timeIntervalSince1970: 1)
        )
        let second = ClipboardCandidate(
            payload: .text("hello\nworld"),
            source: source,
            capturedAt: Date(timeIntervalSince1970: 2)
        )
        let a = try ClipboardContentNormalizer.normalized(candidate: first)
        let b = try ClipboardContentNormalizer.normalized(candidate: second)
        expect(a.contentHash == b.contentHash, "line endings must normalize before hashing")
        expect(a.plainText == "hello\nworld", "normalized text must be stored")

        let link = try ClipboardContentNormalizer.normalized(candidate: ClipboardCandidate(
            payload: .link(URL(string: "HTTPS://Example.COM/path")!),
            source: source,
            capturedAt: .now
        ))
        expect(
            link.kind == .link && link.plainText == "https://example.com/path",
            "links must have a canonical representation"
        )

        let files = try ClipboardContentNormalizer.normalized(candidate: ClipboardCandidate(
            payload: .files([
                URL(fileURLWithPath: "/tmp/a"),
                URL(fileURLWithPath: "/tmp/b")
            ]),
            source: source,
            capturedAt: .now
        ))
        expect(
            files.fileURLs.count == 2 && files.kind == .files,
            "file order and type must survive normalization"
        )

        expectThrowsEmptyContent()
        checkPrivacyPolicy()
        checkRetentionPolicy()
        print("✅ ClipboardHistoryCoreChecks passed")
    }

    private static func checkPrivacyPolicy() {
        let privacy = ClipboardPrivacyPolicy(excludedBundleIDs: ["com.example.private"])
        expect(
            privacy.decision(
                kind: .text,
                typeNames: ["org.nspasteboard.ConcealedType"],
                sourceBundleID: nil,
                payloadBytes: 10
            ) == .reject(.sensitiveType),
            "concealed content must be rejected"
        )
        expect(
            privacy.decision(
                kind: .text,
                typeNames: ["org.nspasteboard.TransientType"],
                sourceBundleID: nil,
                payloadBytes: 10
            ) == .reject(.sensitiveType),
            "transient content must be rejected"
        )
        expect(
            privacy.decision(
                kind: .text,
                typeNames: ["org.nspasteboard.AutoGeneratedType"],
                sourceBundleID: nil,
                payloadBytes: 10
            ) == .reject(.sensitiveType),
            "auto-generated content must be rejected"
        )
        expect(
            privacy.decision(
                kind: .text,
                typeNames: ["public.utf8-plain-text"],
                sourceBundleID: "com.example.private",
                payloadBytes: 10
            ) == .reject(.excludedApplication),
            "excluded apps must be rejected"
        )
        expect(
            privacy.decision(
                kind: .text,
                typeNames: ["public.utf8-plain-text"],
                sourceBundleID: nil,
                payloadBytes: 1_048_577
            ) == .reject(.tooLarge),
            "oversized text must be rejected"
        )
        expect(
            privacy.decision(
                kind: .image,
                typeNames: ["public.png"],
                sourceBundleID: nil,
                payloadBytes: 40 * 1_024 * 1_024 + 1
            ) == .reject(.tooLarge),
            "oversized images must be rejected"
        )
        expect(
            privacy.decision(
                kind: .files,
                typeNames: ["public.file-url"],
                sourceBundleID: nil,
                payloadBytes: 2_000_000
            ) == .accept,
            "file metadata is not subject to content-size limits"
        )
    }

    private static func checkRetentionPolicy() {
        let now = Date(timeIntervalSince1970: 4_000_000)
        let items = makeRetentionFixtures(now: now, normalCount: 502, favoriteCount: 1)
        let evictions = ClipboardRetentionPolicy.default.evictionIDs(
            items: items,
            assetBytes: 0,
            now: now
        )
        expect(evictions.count == 2, "count limit must evict oldest non-favorites")
        expect(
            evictions == [items[0].id, items[1].id],
            "count eviction must be oldest first"
        )
        expect(!evictions.contains(items.last!.id), "favorites must survive count eviction")

        let expired = makeItem(
            index: 10_000,
            kind: .text,
            updatedAt: now.addingTimeInterval(-(31 * 24 * 60 * 60)),
            isFavorite: false,
            byteSize: 10
        )
        let expiredFavorite = makeItem(
            index: 10_001,
            kind: .image,
            updatedAt: now.addingTimeInterval(-(60 * 24 * 60 * 60)),
            isFavorite: true,
            byteSize: 500
        )
        let ageEvictions = ClipboardRetentionPolicy.default.evictionIDs(
            items: [expired, expiredFavorite],
            assetBytes: 500,
            now: now
        )
        expect(ageEvictions == [expired.id], "age cleanup must preserve favorites")

        let oldImage = makeItem(
            index: 20_000,
            kind: .image,
            updatedAt: now.addingTimeInterval(-20),
            isFavorite: false,
            byteSize: 80
        )
        let newImage = makeItem(
            index: 20_001,
            kind: .image,
            updatedAt: now.addingTimeInterval(-10),
            isFavorite: false,
            byteSize: 50
        )
        let tinyPolicy = ClipboardRetentionPolicy(maxCount: 500, maxAge: 30 * 24 * 60 * 60, maxAssetBytes: 100)
        expect(
            tinyPolicy.evictionIDs(items: [newImage, oldImage], assetBytes: 130, now: now) == [oldImage.id],
            "asset cleanup must evict the oldest eligible image until under the limit"
        )
    }

    private static func expectThrowsEmptyContent() {
        let source = ClipboardSource(appName: nil, bundleID: nil)
        do {
            _ = try ClipboardContentNormalizer.normalized(candidate: ClipboardCandidate(
                payload: .text(""),
                source: source,
                capturedAt: .now
            ))
            fatalError("❌ empty text must be rejected")
        } catch ClipboardNormalizationError.emptyContent {
            // Expected.
        } catch {
            fatalError("❌ wrong empty-content error: \(error)")
        }
    }

    static func expect(_ condition: @autoclosure () -> Bool, _ message: String) {
        guard condition() else { fatalError("❌ \(message)") }
    }

    private static func makeRetentionFixtures(
        now: Date,
        normalCount: Int,
        favoriteCount: Int
    ) -> [ClipboardItem] {
        let normal = (0..<normalCount).map { index in
            makeItem(
                index: index,
                kind: .text,
                updatedAt: now.addingTimeInterval(TimeInterval(-normalCount + index)),
                isFavorite: false,
                byteSize: 10
            )
        }
        let favorites = (0..<favoriteCount).map { index in
            makeItem(
                index: normalCount + index,
                kind: .image,
                updatedAt: now.addingTimeInterval(TimeInterval(index)),
                isFavorite: true,
                byteSize: 1_000
            )
        }
        return normal + favorites
    }

    private static func makeItem(
        index: Int,
        kind: ClipboardItemKind,
        updatedAt: Date,
        isFavorite: Bool,
        byteSize: Int64
    ) -> ClipboardItem {
        ClipboardItem(
            id: UUID(uuidString: String(format: "00000000-0000-0000-0000-%012d", index))!,
            kind: kind,
            contentHash: "hash-\(index)",
            plainText: "item \(index)",
            assetPath: kind == .image ? "\(index).png" : nil,
            fileURLs: [],
            source: ClipboardSource(appName: nil, bundleID: nil),
            createdAt: updatedAt,
            updatedAt: updatedAt,
            lastRestoredAt: nil,
            isFavorite: isFavorite,
            byteSize: byteSize
        )
    }
}
